services:
  traefik:
    privileged: true
    image: traefik:latest
    container_name: traefik
    networks:
      - dslab-net
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Redirection auto HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:z
      - ./dslab.crt:/etc/traefik/dslab.crt:ro
      - ./dslab.key:/etc/traefik/dslab.key:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
    labels:
      - "traefik.http.providers.file.filename=/etc/traefik/traefik_dynamic.yml"

  dslab-web:
    build: .
    container_name: dslab_web
    volumes:
      - /home/lisa/DSLab:/app/data:Z
    env_file:
      - .env
    depends_on:
      - traefik
    networks:
      - dslab-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dslab.rule=PathPrefix(`/`) && !PathPrefix(`/hub`) && !PathPrefix(`/user`)"
      - "traefik.http.routers.dslab.entrypoints=websecure"
      - "traefik.http.routers.dslab.tls=true"
      - "traefik.http.services.dslab.loadbalancer.server.port=8090"

  jupyterhub:
    # On peut aussi conteneuriser JupyterHub ou le laisser sur l'hôte
    # Si JupyterHub est sur l'hôte, on utilise un 'provider' file dans traefik
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    privileged: true
    container_name: jupyterhub
    entrypoint: >
      sh -c "chmod 666 /var/run/docker.sock && 
             jupyterhub -f /srv/jupyterhub/jupyterhub_config.py"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hub.rule=PathPrefix(`/hub`) || PathPrefix(`/user`)"
      - "traefik.http.routers.hub.entrypoints=websecure"
      - "traefik.http.services.hub.loadbalancer.server.port=8000"
    volumes:
      - /home/lisa/DSLab/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:z
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:z
      - /home/lisa/DSLab:/mnt/db:ro,z
    networks:
      dslab-net:
        aliases:
          - jupyterhub

networks:
  dslab-net:
    name: dslab-net # On force le nom ici
    driver: bridge
